In [1]:
import numpy as np
import pandas as pd
import scipy
from collections import OrderedDict
from sklearn import preprocessing
import joblib as jb
import random
import time
from IPython.display import clear_output

In [2]:
#Creando los 10 features y las constantes necesarias
features=['A','B','C','D','F','G','H','I','j','k']


In [3]:
model=jb.load('rfDefense2021.sav')
print(model)

RandomForestClassifier(max_depth=50, n_estimators=250, random_state=45)


In [4]:
#tabla de pandas
df=pd.DataFrame(columns=features)
print(df)

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []


In [5]:
df

Empty DataFrame
Columns: [A, B, C, D, F, G, H, I, j, k]
Index: []

In [6]:
def generateValuesV2(malwItems):
    flag=False
    maxLoss=0
    a=0
    valuesToTest=np.array([0,0,0,0,0,0,0,0,0,0])
    
    
    while a<malwItems:   
        
        if flag==False:
          
          valuesToTest=np.array([])
          for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
          
          temporalx=valid(valuesToTest,a)  
          a=a+temporalx
          
          if temporalx==1:
            flag=True
            maxLoss=0
            
          
        elif flag==True:
          
          temp=np.array([])
          for x in range(10):
            temp=np.append(temp, random.randint(-2,2))
            
          outarr=np.add(temp,valuesToTest)
          print('enter')
          a=a+valid(outarr,a)
          if(maxLoss==10):
            flag=False
          maxLoss=maxLoss+1
    
    
    

In [7]:
def valid(valuesToTest,a):
    result=None
    val=0
    try:
        result=model.predict(valuesToTest.reshape(1,-1))
        result=np.array2string(result)
        #print(valuesToTest.reshape(1,-1))
    except Exception as ex:
       pass 
    
    if result=="['malicious']":
        print(a+1)
        formatier=valuesToTest.reshape(1,-1)[0]
        df.loc[a]=formatier
        print(formatier)
        val=1
    return val

In [8]:

def generateValues(malwItems):
    
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        result=None
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-100,100))
                    
        try:
             result=model.predict(valuesToTest.reshape(1,-1))
             result=np.array2string(result)
             #print(valuesToTest.reshape(1,-1))
        except Exception as ex:
           pass 
        
        if result=="['malicious']":
            
            formatier=valuesToTest.reshape(1,-1)[0]
            df.loc[a]=formatier
            a=a+1
            print(formatier)
            print(a-1)
       

In [9]:

def generateValuesV3(malwItems):
    
    a=0
    while a<malwItems:
        
        valuesToTest=np.array([])
        for x in range(10):
            valuesToTest=np.append(valuesToTest, random.randint(-50,50))
                    
        a=a+valid(valuesToTest,a)

In [10]:
#generateValuesV3(3)

In [11]:
#generateValues(3)

In [15]:
generateValuesV2(500)

1
[-39. -99. -64.  33. -28. -50. -63.  21. -97.  33.]
enter
2
[-38. -98. -65.  31. -28. -51. -61.  21. -96.  31.]
enter
3
[ -40. -101.  -64.   33.  -26.  -48.  -63.   19.  -98.   32.]
enter
4
[ -39. -101.  -62.   32.  -30.  -50.  -64.   20.  -95.   33.]
enter
5
[-39. -97. -63.  33. -30. -52. -64.  23. -95.  33.]
enter
6
[ -41. -100.  -63.   32.  -29.  -48.  -65.   22.  -97.   34.]
enter
7
[-41. -99. -66.  31. -28. -50. -62.  22. -98.  32.]
enter
8
[-38. -99. -65.  33. -27. -50. -63.  20. -97.  35.]
enter
9
[-40. -97. -66.  31. -30. -49. -61.  23. -97.  35.]
enter
10
[-40. -99. -62.  35. -28. -50. -62.  21. -96.  34.]
enter
11
[ -40. -101.  -63.   33.  -28.  -48.  -61.   20.  -95.   33.]
enter
12
[-38. -97. -65.  32. -30. -48. -64.  22. -96.  34.]
13
[-88. -81. -75. -67. -39.  35. -57.  25. -62.  44.]
enter
14
[-87. -83. -76. -66. -37.  37. -57.  26. -61.  44.]
enter
15
[-89. -81. -74. -67. -40.  35. -58.  24. -61.  42.]
enter
16
[-90. -83. -73. -65. -38.  33. -58.  23. -60.  43.]
enter

In [ ]:
#generateValues(1500)
#clear_output(wait=True)

In [ ]:
df

A     B      C     D     F     G     H     I     j      k
0   -22.0  98.0 -100.0  66.0 -80.0  91.0  63.0   1.0  86.0  100.0
1   -20.0  99.0 -101.0  67.0 -81.0  93.0  61.0   0.0  84.0  100.0
2   -21.0  99.0  -98.0  64.0 -78.0  93.0  61.0   1.0  86.0  100.0
3   -24.0  98.0 -102.0  67.0 -78.0  89.0  64.0   3.0  88.0   98.0
4   -22.0  99.0  -98.0  64.0 -81.0  91.0  62.0   0.0  88.0   99.0
..    ...   ...    ...   ...   ...   ...   ...   ...   ...    ...
995 -98.0 -39.0  -33.0 -10.0  59.0   2.0 -30.0  85.0 -14.0   79.0
996 -99.0 -36.0  -33.0  -9.0  59.0   1.0 -30.0  83.0 -16.0   79.0
997 -97.0 -39.0  -36.0 -10.0  63.0   3.0 -30.0  83.0 -17.0   77.0
998 -99.0 -38.0  -34.0  -7.0  59.0   1.0 -29.0  87.0 -15.0   78.0
999 -97.0 -37.0  -33.0  -6.0  62.0   0.0 -29.0  87.0 -14.0   78.0

[1000 rows x 10 columns]

In [ ]:
df.to_csv('datasets/malicious_data_generated.csv' ,header=False,index=False)