In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import swifter
#from model import DeepMALDRL
from tensorflow.keras.models import load_model

In [2]:
deepMAL = load_model('deep_mal_v5.h5')

In [3]:
print(deepMAL.summary())

Model: "DeepMAL-Packets"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1024, 1)]         0         
                                                                 
 conv1d (Conv1D)             (None, 1020, 32)          192       
                                                                 
 conv1d_1 (Conv1D)           (None, 1016, 64)          10304     
                                                                 
 max_pooling1d (MaxPooling1D  (None, 127, 64)          0         
 )                                                               
                                                                 
 lstm (LSTM)                 (None, 127, 200)          212000    
                                                                 
 flatten (Flatten)           (None, 25400)             0         
                                                   

In [4]:
asproxOld = pd.read_csv('output-TrojanAsproxOld.csv', header=0)
asproxNew = pd.read_csv('output-TrojanAsproxNew.csv', header=0)
electroRAT = pd.read_csv('output-AllElectroRAT.csv', header=0)

In [5]:
print("AsproxOld data length: ", len(asproxOld))
print("AsproxNew data length: ", len(asproxNew))
print("ElectroRAT data length: ", len(electroRAT))

AsproxOld data length:  36
AsproxNew data length:  32
ElectroRAT data length:  55


In [6]:
asproxOld['udps.n_bytes_per_packet'] = asproxOld['udps.n_bytes_per_packet'].swifter.apply(eval)
asproxNew['udps.n_bytes_per_packet'] = asproxNew['udps.n_bytes_per_packet'].swifter.apply(eval)
electroRAT['udps.n_bytes_per_packet'] = electroRAT['udps.n_bytes_per_packet'].swifter.apply(eval)

Pandas Apply:   0%|          | 0/36 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/32 [00:00<?, ?it/s]

Pandas Apply:   0%|          | 0/55 [00:00<?, ?it/s]

In [7]:
asproxOld= asproxOld.explode('udps.n_bytes_per_packet', ignore_index=True)
asproxNew= asproxNew.explode('udps.n_bytes_per_packet', ignore_index=True)
electroRAT= electroRAT.explode('udps.n_bytes_per_packet', ignore_index=True)

In [20]:
#data = list(malware_data['udps.n_bytes_per_packet'])

In [9]:
predictionsAsproxOld = deepMAL.predict(list(asproxOld['udps.n_bytes_per_packet']))
predictionsAsproxNew = deepMAL.predict(list(asproxNew['udps.n_bytes_per_packet']))
predictionsElectroRAT = deepMAL.predict(list(electroRAT['udps.n_bytes_per_packet']))

10/10 [==============================] - 1s 133ms/step


In [10]:
predictionsAsproxOld

array([[0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.90869564],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.87181115],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [1.        ],
       [1.        ],
       [0.98555195],
       [0.9992641 ],
       [0.9993358 ],
       [0.9971792 ],
       [0.99867266],
       [0.9982739 ],
       [0.99575746],
       [0.9869826 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [1.        ],
       [1.        ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.99388534],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.852

In [11]:
predictionsAsproxNew

array([[0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.97498155],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.87471443],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [1.        ],
       [1.        ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [1.        ],
       [1.        ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [1.        ],
       [1.        ],
       [0.98555195],
       [0.99815655],
       [0.9982316 ],
       [0.9758224 ],
       [0.99594593],
       [0.99831945],
       [0.946139  ],
       [0.96981335],
       [0.8522252 ],
       [0.8522252 ],
       [0.852

In [12]:
predictionsElectroRAT

array([[0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.99999136],
       [0.8522252 ],
       [0.9999865 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.87471443],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.9999963 ],
       [0.8522252 ],
       [0.98739535],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.8522252 ],
       [0.8522252 ],
       [0.8522252 ],
       [0.99991643],
       [0.8522252 ],
       [0.99998933],
       [0.8522252 ],
       [0.8522252 ],
       [0.852

In [17]:
predictionsAsproxOld[predictionsAsproxOld>0.5] = 1 #malware
predictionsAsproxOld[predictionsAsproxOld<=0.5] = 0 #benign

print(sum(predictionsAsproxOld), len(predictionsAsproxOld))

[144.] 144


In [16]:
predictionsAsproxNew[predictionsAsproxNew>0.5] = 1 #malware
predictionsAsproxNew[predictionsAsproxNew<=0.5] = 0 #benign

print(sum(predictionsAsproxNew), len(predictionsAsproxNew))

[133.] 133


In [18]:
predictionsElectroRAT[predictionsElectroRAT>0.5] = 1 #malware
predictionsElectroRAT[predictionsElectroRAT<=0.5] = 0 #benign

print(sum(predictionsElectroRAT), len(predictionsElectroRAT))

[314.] 314
